name: Ruff Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with dev

      - name: Run Ruff
        run: poetry run ruff check
